# Generated by Django 3.1.7 on 2021-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0007_auto_20210510_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='add_date',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAdress',
        ),
    ]
